services:
  - type: web
    name: caption_project
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn caption_project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
